# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "training" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Get Diffs
        id: get_diffs
        env:
          $ENV: ${{ github.ref_name }}
          $MASTER: "main"
        run: |
          git fetch
          GIT_DIF=$(env -i git --no-pager log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr)%Creset %C(bold blue)<%an>%Creset' --abbrev-commit --date=relative origin/$ENV..origin/$MASTER) 
          echo "changelog=$GIT_DIF" >> $GITHUB_OUTPUT

      # Runs a set of commands using the runners shell
      - name: Notion release notes
        uses: infinitaslearning/notion-release-notes@main
        with:
          token: ${{ secrets.NOTION_TOKEN }}
          database: ${{ secrets.DB_NOTION }}
          name: ${{ github.event.head_commit.message }}
          tags: ${{ github.ref_name }}
          body: ${{ steps.get_diffs.outputs.changelog }}
